# fly.toml app configuration file generated for sectors-news-endpoint on 2024-08-08T20:55:57+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'sectors-news-endpoint'
primary_region = 'sin'

[build]

[http_service]
  internal_port = 8080
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '2gb'
  cpu_kind = 'shared'
  cpus = 1
